#######################################################
# API                                                 #
#######################################################

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: contosomaintenance-api
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: contosomaintenance-api
    spec:
      containers:
        - name: contosomaintenance-api
          image: robinmanuelthiel/contosomaintenance-api
          env:
            - name: AzureCosmosDb__Endpoint
              valueFrom:
                secretKeyRef:
                  name: appsettings
                  key: AzureCosmosDb__Endpoint
            - name: AzureCosmosDb__Key
              valueFrom:
                secretKeyRef:
                  name: appsettings
                  key: AzureCosmosDb__Key      
            - name: AzureStorage__StorageAccountName
              valueFrom:
                secretKeyRef:
                  name: appsettings
                  key: AzureStorage__StorageAccountName      
            - name: AzureStorage__Key
              valueFrom:
                secretKeyRef:
                  name: appsettings
                  key: AzureStorage__Key      
            - name: ActiveDirectory__Tenant
              valueFrom:
                secretKeyRef:
                  name: appsettings
                  key: ActiveDirectory__Tenant     
            - name: ActiveDirectory__ApplicationId
              valueFrom:
                secretKeyRef:
                  name: appsettings
                  key: ActiveDirectory__ApplicationId     
            - name: ActiveDirectory__SignUpSignInPolicy
              valueFrom:
                secretKeyRef:
                  name: appsettings
                  key: ActiveDirectory__SignUpSignInPolicy     
            - name: ApplicationInsights__InstrumentationKey
              valueFrom:
                secretKeyRef:
                  name: appsettings
                  key: ApplicationInsights__InstrumentationKey        
          ports:
          - containerPort: 80
          - containerPort: 443
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: contosomaintenance-api
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
  selector:
    app: contosomaintenance-api
---

#######################################################
# Chatbot                                             #
#######################################################

apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: contosomaintenance-bot
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: contosomaintenance-bot
    spec:
      containers:
        - name: contosomaintenance-bot
          image: robinmanuelthiel/contosomaintenance-bot
          ports:
          - containerPort: 80
          - containerPort: 443
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: contosomaintenance-bot
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
  selector:
    app: contosomaintenance-bot
