apiVersion: v1
kind: Service
metadata:
  name: contosomaintenance-bot
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
  - name: https
    port: 443
  selector:
    app: contosomaintenance-bot